### PR TITLE
Propagate alignment to Hero block inner buttons

### LINKED ISSUE #1460: Hero block's button doesn't center on selection
### Describe the bug:
When adding the Hero block the buttons do not align with users choices.

### To reproduce:

1. Install plugin
2. Go to a page
3. Add Hero block, remove the second button,
Screen Shot
 and select center layout
4. Publish page
5. Scroll until Hero block is in view
6. See error

### Expected behavior:
When the center layout option is selected, the Hero button should also readjust

### Isolating the problem:

- [ x] This bug happens with no other plugins activated
- [x ] This bug happens with a default WordPress theme active
- [x ] This bug happens **without** the Gutenberg plugin active
- [ x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.4

### Extra Possibly Useful Information
- Theme: Storefront

### PR DESCRIPTION
**Pull request by AnthonyLedesma**
### Description
PR to set inner block button alignment with Hero block. 
Closes #1460.

### Types of changes

Add Select and Dispatch HOC to Grid component to allow setting of inner block attributes. 

### How has this been tested?

Tested in 5.4 with and without the Gutenberg plugin.

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

### CODE REVIEW

File: src/js/deprecations/deprecate-coblocks-buttons.js [hunk 1]
```diff
@@ -4,28 +4,43 @@
 import { getBlockType, registerBlockType, unregisterBlockType } from '@wordpress/blocks';
```
Comment (richtabor) [inline src/js/deprecations/deprecate-coblocks-buttons.js:4]: Is modifying this necessary?
