### PR TITLE
Fix invisble block states enabled by animation class

### LINKED ISSUE #1941: ISNBAT enable invisible block states with `coblocks-animate` class
### Describe the bug:

Discovered in https://github.com/godaddy-wordpress/coblocks/issues/1879 but not officially reported is a situation where the Media and Text block is able to enter an unusable state. This can only happen when the CoBlocks plugin is disabled and re-enabled later. While perhaps not a typical user interaction, the enabling and disabling of common plugins are steps that many developers take when simply troubleshooting website issues. It is reasonable to believe this situation could happen in the wild and should be handled as a sort of deprecation hopefully.

This behavior occurs with the 'core/media-text' 'core/image' 'core/group' 'core/gallery' 'core/cover' and 'core/columns' blocks.

### To reproduce:

1. Create new post and add the Media and Text block.
2. Edit the Media and Text block to have an image and enable any of the animation control settings.
3. Save post.
4. Using WP-CLI we first disable CoBlocks. `wp plugin deactivate coblocks`
5. Reload post and notice (expected) block error. Attempt block recovery. Save post.
6. Using WP-CLI we activate CoBlocks. `wp plugin active coblocks`
7. Reload post and notice that Media and Text are hidden with `opacity: 0`.
8. Notice that attributes are not parsed due to user interaction to Attempt block recovery.

### Expected behavior:

This interaction is a complicated one but the UX impact is quite large with hidden blocks in the editor.

### Screenshots:

image

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

5.7.2

### Gutenberg version:

N/A

### PR DESCRIPTION
**Pull request by snovosel**
Fixes #1941 

### Description

If an animation (coblocks extension) is added to a block, and the coblocks plugin is deactivated, block validation will fail and block recovery will remove the animation attribute, however the classname `coblocks-animate` will be kept. If coblocks is re-activated , as the animation is undefined and the className is set, an opacity of 0 is set to the block. This PR attempts to add a block filter to remove this class name in the event of an undefined animation attribute.

### Types of changes

Bug fix

### How has this been tested?

visually

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

### CODE REVIEW

File: src/extensions/animation/index.js [hunk 1]
```diff
@@ -186,3 +186,23 @@ addFilter(
 	'coblocks/withAnimationSettings',
 	withAnimationSettings
 );
+
+const ALLOWED_ANIMATION_BLOCKS = [ 'core/media-text' ];
```
Comment (jlemay-godaddy) [inline src/extensions/animation/index.js:190]: What is it doing? If it's checking for blocks with animation enabled, there are a lot more

Comment (snovosel) [reply src/extensions/animation/index.js:190]: Should we open this up to remove the animate class name if the animation is undefined for all blocks? According to the issue, this is a problem for the following blocks:

```
'core/media-text',
	'core/image',
	'core/group',
	'core/gallery',
	'core/cover',
	'core/columns'
```

Comment (jlemay-godaddy) [reply src/extensions/animation/index.js]: If the problem has a chance to happen, we should ensure that it won't. So yeah, I would target all the blocks that are animation-capable

**Review by AnthonyLedesma — APPROVED** [review]
LGTM.
Pushed up some major changes to exclude use of an addtional filter.
