### PR TITLE
Fix editor crash when running CoBlocks and WordPress 5.4.2

### LINKED ISSUE #1666: Editor completely broken in WordPress 5.4.2
### Describe the bug:
I should be able to use the editor.

### To reproduce:
Clean install of Wordpress 5.4.2 with only CoBlocks activated and standard TwentyTwenty theme. Go to add new post and get blank screen with error message "The editor has encountered an unexpected error." Error in Chrome dev tools shows "Minified React error #130".

### Expected behavior:
The editor should appear.

### Screenshots:
Screenshot 2020-09-04 at 12 28 05
Screenshot 2020-09-04 at 12 28 13

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [N/A] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.4.2

### Gutenberg version:
N/A

### PR DESCRIPTION
**Pull request by AnthonyLedesma**
### Description

CoBlocks has implemented components that are bundled natively with WordPress 5.5 but which are not bundled with 5.4.2 resulting in editor crash when editing or adding a new post.

Closes #1666.

This PR adds new logic to conditionally load Block-Patten extension.

### Types of changes

Logic to PHP and JavaScript to conditonally load block patterns extension.

### How has this been tested?

Tested manually using WordPress 5.4.2 as well as 5.5.

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

### CODE REVIEW

File: includes/class-block-patterns.php [hunk 1]
```diff
@@ -23,14 +23,21 @@ class CoBlocks_Block_Patterns {
...
-		add_action( 'init', array( $this, 'load_block_patterns' ) );
-		add_action( 'rest_insert_' . self::POST_TYPE, array( $this, 'add_taxonomies_on_insert_post' ), 10, 2 );
-
-		add_filter( 'coblocks_layout_selector_categories', array( $this, 'load_categories' ) );
-		add_filter( 'coblocks_layout_selector_layouts', array( $this, 'load_layouts' ) );
+		global $wp_version;
+		$version = str_replace( '-src', '', $wp_version );  // Strip '-src' from the version string. Messes up version_compare().
+		add_action( 'admin_enqueue_scripts', array( $this, 'conditional_load_patterns' ) );
+		
+		if ( version_compare( $version, '5.5-beta', '>=' ) ) {
```
Comment (jrtashjian) [inline includes/class-block-patterns.php:30]: We shouldn't need to do any checks on the version string. Let's utilize the built-in function [`is_wp_version_compatible`](https://developer.wordpress.org/reference/functions/is_wp_version_compatible/) here instead to simplify.

File: includes/class-block-patterns.php [hunk 2]
```diff
@@ -104,6 +111,24 @@ public function add_taxonomies_on_insert_post( $post, $request ) {
...
+	 */
+	public function conditional_load_patterns() {
+		global $wp_version;
+		$version = str_replace( '-src', '', $wp_version ); // Strip '-src' from the version string. Messes up version_compare().
+
+		wp_localize_script(
+			'coblocks-editor',
+			'coblocksBlockPatterns',
+			array(
+				'patternsEnabled' => version_compare( $version, '5.5-beta', '>=' ),
```
Comment (jrtashjian) [inline includes/class-block-patterns.php:127]: Let's utilize the built-in function [`is_wp_version_compatible`](https://developer.wordpress.org/reference/functions/is_wp_version_compatible/) here instead to simplify.

**Review by jrtashjian — CHANGES_REQUESTED** [review]
Just a couple changes and it'll be ready.

**Review by jrtashjian — APPROVED** [review]
