### PR TITLE
Remove Typography controls from the core Cover block

### LINKED ISSUE #947: ISNBAT set Cover block Typography Controls
**Describe the bug**
At this time the Cover block has CoBlocks Typography Controls functionality. This is an issue because the Typography Controls are already given to any Inner blocks (Heading, Paragraph) thus  having the functionality on Cover block is adds complexity and redundancy and should be disabled.

**To Reproduce**

1. Add Cover block.
2. Click block and view toolbar.
3. Notice icon for Typography Controls.

**Screenshots**
Typography Controls icon within the toolbar. 
image

**Expected behavior**
We should find a way to disable the additional functionality for Cover block but allow for inner blocks. We should also ensure that block deprecations are created if needed. 

An experimental branch has been started under `remove-text-settings-coverblock` where some work has been completed. Beware of missing deprecation in this branch. 

**Isolating the problem:**
Mark completed items with an [x].

-   [X] This bug happens with no other plugins activated
-   [X] This bug happens with a default WordPress theme active
-   [X] This bug happens **without** the Gutenberg plugin active
-   [X] I can reproduce this bug consistently using the steps above

**WordPress Version**
What version of WordPress are you using?
5.2.3

**Gutenberg Version**
What version of the Gutenberg plugin are you using? (If any)
N/A

### PR DESCRIPTION
**Pull request by richtabor**
This PR removes the Typography controls from the core Cover block, as the Cover block contains InnerBlocks blocks which already have Type controls.

Closes #947.

### CODE REVIEW

**Comment by richtabor** [comment]
> It looks like if a core/cover block has been adjusted then this would cause validation errors.

100%. I adjusted the technique to only hide the control for the cover block, instead of removing it entirely - preventing the block from breaking validation. Mind giving it a re-review @AnthonyLedesma?

File: src/extensions/typography/index.js [hunk 1]
```diff
@@ -20,7 +20,7 @@ import { addFilter } from '@wordpress/hooks';
 import { Fragment }	from '@wordpress/element';
 import { compose, createHigherOrderComponent } from '@wordpress/compose';
 
-const allowedBlocks = [ 'core/paragraph', 'core/heading', 'core/cover', 'core/pullquote', 'core/quote', 'core/button', 'core/list', 'coblocks/row', 'coblocks/column', 'coblocks/accordion', 'coblocks/accordion-item', 'coblocks/click-to-tweet', 'coblocks/alert', 'coblocks/highlight', 'coblocks/pricing-table', 'coblocks/features' ];
+const allowedBlocks = [ 'core/paragraph', 'core/heading', 'core/pullquote', 'core/cover', 'core/quote', 'core/button', 'core/list', 'coblocks/row', 'coblocks/column', 'coblocks/accordion', 'coblocks/accordion-item', 'coblocks/click-to-tweet', 'coblocks/alert', 'coblocks/highlight', 'coblocks/pricing-table', 'coblocks/features' ];
```
Comment (AnthonyLedesma) [inline src/extensions/typography/index.js]: Should this `allowedBlocks` array match the array found in `src/components/typography-controls/index.js`?

```javascript
const allowedBlocks = [ 'core/paragraph', 'core/heading', 'core/button', 'core/list', 'coblocks/row', 'coblocks/column', 'coblocks/accordion', 'coblocks/accordion-item', 'coblocks/click-to-tweet', 'coblocks/alert', 'coblocks/pricing-table', 'coblocks/highlight', 'coblocks/features' ];
```
