### PR TITLE
WPEX-1459 - do not throw error on custom entered category for post carousel and posts block

### LINKED ISSUE #1974: ISNBAT crash the Posts and Post Carousel block by using an invalid category id
### Describe the bug:

When choosing a category on the Posts or Post Carousel blocks a user might not select a token value and instead enter in a custom value followed by a keyboard return. This results in a block error state.

### To reproduce:

1. Add Posts block.
2. Open block sidebar and feed settings.
3. Type in a bogus category and hit return to see the error.

### Expected behavior:

Expect error notice perhaps or save the value and take no action. Block errors should not occur.

### Screenshots:

postCrashWithCategory

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

5.8

### Gutenberg version:

N/A

### PR DESCRIPTION
**Pull request by snovosel**
### Description

This PR handles the use case of a custom category entered into the feed settings for both the Posts and Post Carousel block. If an unrecognized, custom category is entered then no action is taken and no block error will be thrown.

Fixes #1974 

### Types of changes

Bug fix

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

### CODE REVIEW

File: src/blocks/post-carousel/edit.js [hunk 1]
```diff
@@ -356,7 +356,12 @@ export default compose( [
 
 		const updatedQuery = () => {
 			const catIds = categories && categories.length > 0
-				? categories.map( ( cat ) => cat.id )
+				? categories.map( ( cat ) => {
+					if ( ! cat ) {
+						return null;
+					}
+					return cat.id;
+				} )
```
Comment (AnthonyLedesma) [inline src/blocks/post-carousel/edit.js:364]: This can be simplified to `? categories.map( ( cat ) => cat?.id )`

Comment (AnthonyLedesma) [reply src/blocks/post-carousel/edit.js:364]: Is this same change needed within `src/blocks/posts/edit.js`?

**Review by AnthonyLedesma — DISMISSED** [review]
Things are working well and the bug seems to be resolved. Question on one of the changes that you have made to an edit function.

**Review by AnthonyLedesma — APPROVED** [review]
LGTM
